package protocol

const (
	PROTOCOL_SUM_REQUEST    = 1
	PROTOCOL_SUM_REPLY      = 2
	PROTOCOL_CONCAT_REQUEST = 3
	PROTOCOL_CONCAT_REPLY   = 4
	PROTOCOL_MATCH_REQUEST  = 5
	PROTOCOL_MATCH_REPLY    = 6
)

var PROTOCOL_METHOD_MAP = map[int32]string{
	PROTOCOL_SUM_REQUEST:    "Sum",
	PROTOCOL_CONCAT_REQUEST: "Concat",
	PROTOCOL_MATCH_REQUEST:  "Match",
}

var METHOD_PROTOCOL_MAP = map[string]int32{
	"Sum":    PROTOCOL_SUM_REQUEST,
	"Concat": PROTOCOL_CONCAT_REQUEST,
	"Match":  PROTOCOL_MATCH_REQUEST,
}
